const jayson = require("jayson/promise");
const client =  jayson.client.http("http://localhost:5535/bob/jsonrpc");
const fs = require('mz/fs');

const alicePubKey = "032a2b53cd473887e468f4c5cdb5e490e01e590694824678c4b091734184e82eb9";
const bobPubKey = "028854e1eb5d17c22c25712ca89b35b03223480971a88e7b573441cfa2b72f891d";

let chainID;

// Bob is a broker. Alice will invite him to the contract she started.
// Let's read contract chainID from the file which was generated by alice-script.js
fs.readFile('chainID', 'utf8').then( (_chainID) => {
  chainID = _chainID;
  console.log('got chainID', chainID);
  return client.request('getFields', [chainID]);
}).then( response => {
  if (response.error) throw Error("Request was unsuccessful:" + response.error.message);
  
  console.log('Contract fields:', response.result);
  return client.request('getApplicableActions', [chainID]);
}).then(
  response => {
    if (response.error) throw Error("Request was unsuccessful:" + response.error.message);

    console.log('Applicable actions:', response.result);
    console.log("Calling DESCRIBE action...");
    return client.request('performAction', [chainID, 'DESCRIBE', {'DESCRIPTION-PARAM': "Slightly moldy"}])
  })
  .then(  response => {
    if (response.error) throw Error("Request was unsuccessful:" + response.error.message);

    console.log('OK');
  })
.catch( (err) => {
  console.log('Got error', err);
})
